/**
 * 農曆日期模組
 * 提供 2026 年農曆日期對照與節慶資訊
 */

const LUNAR_DATA_2026 = {
    '01-01': { lunar: '初一', festival: null },
    '01-02': { lunar: '初二', festival: null },
    '01-03': { lunar: '初三', festival: null },
    '01-04': { lunar: '初四', festival: null },
    '01-05': { lunar: '初五', festival: null },
    '01-06': { lunar: '初六', festival: null },
    '01-07': { lunar: '初七', festival: '人日' },
    '01-08': { lunar: '初八', festival: null },
    '01-09': { lunar: '初九', festival: null },
    '01-10': { lunar: '初十', festival: null },
    '01-11': { lunar: '十一', festival: null },
    '01-12': { lunar: '十二', festival: null },
    '01-13': { lunar: '十三', festival: null },
    '01-14': { lunar: '十四', festival: null },
    '01-15': { lunar: '十五', festival: '元宵' },
    '01-16': { lunar: '十六', festival: null },
    '01-17': { lunar: '十七', festival: null },
    '01-18': { lunar: '十八', festival: null },
    '01-19': { lunar: '十九', festival: null },
    '01-20': { lunar: '二十', festival: null },
    '01-21': { lunar: '廿一', festival: null },
    '01-22': { lunar: '廿二', festival: null },
    '01-23': { lunar: '廿三', festival: null },
    '01-24': { lunar: '廿四', festival: null },
    '01-25': { lunar: '廿五', festival: null },
    '01-26': { lunar: '廿六', festival: null },
    '01-27': { lunar: '廿七', festival: null },
    '01-28': { lunar: '廿八', festival: null },
    '01-29': { lunar: '廿九', festival: null },
    '01-30': { lunar: '三十', festival: null },
    '02-01': { lunar: '初一', festival: null },
    '02-02': { lunar: '初二', festival: null },
    '02-03': { lunar: '初三', festival: null },
    '02-04': { lunar: '初四', festival: null },
    '02-05': { lunar: '初五', festival: null },
    '02-06': { lunar: '初六', festival: null },
    '02-07': { lunar: '初七', festival: null },
    '02-08': { lunar: '初八', festival: null },
    '02-09': { lunar: '初九', festival: null },
    '02-10': { lunar: '初十', festival: null },
    '02-11': { lunar: '十一', festival: null },
    '02-12': { lunar: '十二', festival: null },
    '02-13': { lunar: '十三', festival: null },
    '02-14': { lunar: '十四', festival: null },
    '02-15': { lunar: '十五', festival: '小年夜' },
    '02-16': { lunar: '十六', festival: '除夕' },
    '02-17': { lunar: '十七', festival: '春節' },
    '02-18': { lunar: '十八', festival: '春節' },
    '02-19': { lunar: '十九', festival: '春節' },
    '02-20': { lunar: '二十', festival: '春節' },
    '02-21': { lunar: '廿一', festival: '春節' },
    '02-22': { lunar: '廿二', festival: '春節' },
    '02-23': { lunar: '廿三', festival: null },
    '02-24': { lunar: '廿四', festival: null },
    '02-25': { lunar: '廿五', festival: null },
    '02-26': { lunar: '廿六', festival: null },
    '02-27': { lunar: '廿七', festival: null },
    '02-28': { lunar: '廿八', festival: null },
    '03-01': { lunar: '廿九', festival: null },
    '03-02': { lunar: '初一', festival: null },
    '03-03': { lunar: '初二', festival: null },
    '03-04': { lunar: '初三', festival: null },
    '03-05': { lunar: '初四', festival: null },
    '03-06': { lunar: '初五', festival: null },
    '03-07': { lunar: '初六', festival: null },
    '03-08': { lunar: '初七', festival: null },
    '03-09': { lunar: '初八', festival: null },
    '03-10': { lunar: '初九', festival: null },
    '03-11': { lunar: '初十', festival: null },
    '03-12': { lunar: '十一', festival: null },
    '03-13': { lunar: '十二', festival: null },
    '03-14': { lunar: '十三', festival: null },
    '03-15': { lunar: '十四', festival: null },
    '03-16': { lunar: '十五', festival: null },
    '03-17': { lunar: '十六', festival: null },
    '03-18': { lunar: '十七', festival: null },
    '03-19': { lunar: '十八', festival: null },
    '03-20': { lunar: '十九', festival: null },
    '03-21': { lunar: '二十', festival: null },
    '03-22': { lunar: '廿一', festival: null },
    '03-23': { lunar: '廿二', festival: null },
    '03-24': { lunar: '廿三', festival: null },
    '03-25': { lunar: '廿四', festival: null },
    '03-26': { lunar: '廿五', festival: null },
    '03-27': { lunar: '廿六', festival: null },
    '03-28': { lunar: '廿七', festival: null },
    '03-29': { lunar: '廿八', festival: null },
    '03-30': { lunar: '廿九', festival: null },
    '03-31': { lunar: '三十', festival: null },
    '04-01': { lunar: '初一', festival: null },
    '04-02': { lunar: '初二', festival: null },
    '04-03': { lunar: '初三', festival: null },
    '04-04': { lunar: '初四', festival: null },
    '04-05': { lunar: '初五', festival: null },
    '04-06': { lunar: '初六', festival: null },
    '04-07': { lunar: '初七', festival: null },
    '04-08': { lunar: '初八', festival: null },
    '04-09': { lunar: '初九', festival: null },
    '04-10': { lunar: '初十', festival: null },
    '04-11': { lunar: '十一', festival: null },
    '04-12': { lunar: '十二', festival: null },
    '04-13': { lunar: '十三', festival: null },
    '04-14': { lunar: '十四', festival: null },
    '04-15': { lunar: '十五', festival: null },
    '04-16': { lunar: '十六', festival: null },
    '04-17': { lunar: '十七', festival: null },
    '04-18': { lunar: '十八', festival: null },
    '04-19': { lunar: '十九', festival: null },
    '04-20': { lunar: '二十', festival: null },
    '04-21': { lunar: '廿一', festival: null },
    '04-22': { lunar: '廿二', festival: null },
    '04-23': { lunar: '廿三', festival: null },
    '04-24': { lunar: '廿四', festival: null },
    '04-25': { lunar: '廿五', festival: null },
    '04-26': { lunar: '廿六', festival: null },
    '04-27': { lunar: '廿七', festival: null },
    '04-28': { lunar: '廿八', festival: null },
    '04-29': { lunar: '廿九', festival: null },
    '04-30': { lunar: '初一', festival: null },
    '05-01': { lunar: '初二', festival: null },
    '05-02': { lunar: '初三', festival: null },
    '05-03': { lunar: '初四', festival: null },
    '05-04': { lunar: '初五', festival: null },
    '05-05': { lunar: '初六', festival: null },
    '05-06': { lunar: '初七', festival: null },
    '05-07': { lunar: '初八', festival: null },
    '05-08': { lunar: '初九', festival: null },
    '05-09': { lunar: '初十', festival: null },
    '05-10': { lunar: '十一', festival: null },
    '05-11': { lunar: '十二', festival: null },
    '05-12': { lunar: '十三', festival: null },
    '05-13': { lunar: '十四', festival: null },
    '05-14': { lunar: '十五', festival: null },
    '05-15': { lunar: '十六', festival: null },
    '05-16': { lunar: '十七', festival: null },
    '05-17': { lunar: '十八', festival: null },
    '05-18': { lunar: '十九', festival: null },
    '05-19': { lunar: '二十', festival: null },
    '05-20': { lunar: '廿一', festival: null },
    '05-21': { lunar: '廿二', festival: null },
    '05-22': { lunar: '廿三', festival: null },
    '05-23': { lunar: '廿四', festival: null },
    '05-24': { lunar: '廿五', festival: null },
    '05-25': { lunar: '廿六', festival: null },
    '05-26': { lunar: '廿七', festival: null },
    '05-27': { lunar: '廿八', festival: null },
    '05-28': { lunar: '廿九', festival: null },
    '05-29': { lunar: '三十', festival: null },
    '05-30': { lunar: '初一', festival: null },
    '05-31': { lunar: '初二', festival: null },
    '06-01': { lunar: '初三', festival: null },
    '06-02': { lunar: '初四', festival: null },
    '06-03': { lunar: '初五', festival: null },
    '06-04': { lunar: '初六', festival: null },
    '06-05': { lunar: '初七', festival: null },
    '06-06': { lunar: '初八', festival: null },
    '06-07': { lunar: '初九', festival: null },
    '06-08': { lunar: '初十', festival: null },
    '06-09': { lunar: '十一', festival: null },
    '06-10': { lunar: '十二', festival: null },
    '06-11': { lunar: '十三', festival: null },
    '06-12': { lunar: '十四', festival: null },
    '06-13': { lunar: '十五', festival: null },
    '06-14': { lunar: '十六', festival: null },
    '06-15': { lunar: '十七', festival: null },
    '06-16': { lunar: '十八', festival: null },
    '06-17': { lunar: '十九', festival: null },
    '06-18': { lunar: '二十', festival: null },
    '06-19': { lunar: '廿一', festival: '端午' },
    '06-20': { lunar: '廿二', festival: null },
    '06-21': { lunar: '廿三', festival: null },
    '06-22': { lunar: '廿四', festival: null },
    '06-23': { lunar: '廿五', festival: null },
    '06-24': { lunar: '廿六', festival: null },
    '06-25': { lunar: '廿七', festival: null },
    '06-26': { lunar: '廿八', festival: null },
    '06-27': { lunar: '廿九', festival: null },
    '06-28': { lunar: '三十', festival: null },
    '06-29': { lunar: '初一', festival: null },
    '06-30': { lunar: '初二', festival: null },
    '07-01': { lunar: '初三', festival: null },
    '07-02': { lunar: '初四', festival: null },
    '07-03': { lunar: '初五', festival: null },
    '07-04': { lunar: '初六', festival: null },
    '07-05': { lunar: '初七', festival: null },
    '07-06': { lunar: '初八', festival: null },
    '07-07': { lunar: '初九', festival: null },
    '07-08': { lunar: '初十', festival: null },
    '07-09': { lunar: '十一', festival: null },
    '07-10': { lunar: '十二', festival: null },
    '07-11': { lunar: '十三', festival: null },
    '07-12': { lunar: '十四', festival: null },
    '07-13': { lunar: '十五', festival: null },
    '07-14': { lunar: '十六', festival: null },
    '07-15': { lunar: '十七', festival: '七夕' },
    '07-16': { lunar: '十八', festival: null },
    '07-17': { lunar: '十九', festival: null },
    '07-18': { lunar: '二十', festival: null },
    '07-19': { lunar: '廿一', festival: null },
    '07-20': { lunar: '廿二', festival: null },
    '07-21': { lunar: '廿三', festival: null },
    '07-22': { lunar: '廿四', festival: null },
    '07-23': { lunar: '廿五', festival: null },
    '07-24': { lunar: '廿六', festival: null },
    '07-25': { lunar: '廿七', festival: null },
    '07-26': { lunar: '廿八', festival: null },
    '07-27': { lunar: '廿九', festival: null },
    '07-28': { lunar: '三十', festival: null },
    '07-29': { lunar: '初一', festival: null },
    '07-30': { lunar: '初二', festival: null },
    '07-31': { lunar: '初三', festival: null },
    '08-01': { lunar: '初四', festival: null },
    '08-02': { lunar: '初五', festival: null },
    '08-03': { lunar: '初六', festival: null },
    '08-04': { lunar: '初七', festival: null },
    '08-05': { lunar: '初八', festival: null },
    '08-06': { lunar: '初九', festival: null },
    '08-07': { lunar: '初十', festival: null },
    '08-08': { lunar: '十一', festival: null },
    '08-09': { lunar: '十二', festival: null },
    '08-10': { lunar: '十三', festival: null },
    '08-11': { lunar: '十四', festival: null },
    '08-12': { lunar: '十五', festival: null },
    '08-13': { lunar: '十六', festival: null },
    '08-14': { lunar: '十七', festival: null },
    '08-15': { lunar: '十八', festival: null },
    '08-16': { lunar: '十九', festival: null },
    '08-17': { lunar: '二十', festival: null },
    '08-18': { lunar: '廿一', festival: null },
    '08-19': { lunar: '廿二', festival: null },
    '08-20': { lunar: '廿三', festival: null },
    '08-21': { lunar: '廿四', festival: null },
    '08-22': { lunar: '廿五', festival: null },
    '08-23': { lunar: '廿六', festival: null },
    '08-24': { lunar: '廿七', festival: null },
    '08-25': { lunar: '廿八', festival: null },
    '08-26': { lunar: '廿九', festival: null },
    '08-27': { lunar: '初一', festival: null },
    '08-28': { lunar: '初二', festival: null },
    '08-29': { lunar: '初三', festival: null },
    '08-30': { lunar: '初四', festival: null },
    '08-31': { lunar: '初五', festival: null },
    '09-01': { lunar: '初六', festival: null },
    '09-02': { lunar: '初七', festival: null },
    '09-03': { lunar: '初八', festival: null },
    '09-04': { lunar: '初九', festival: null },
    '09-05': { lunar: '初十', festival: null },
    '09-06': { lunar: '十一', festival: null },
    '09-07': { lunar: '十二', festival: null },
    '09-08': { lunar: '十三', festival: null },
    '09-09': { lunar: '十四', festival: null },
    '09-10': { lunar: '十五', festival: null },
    '09-11': { lunar: '十六', festival: null },
    '09-12': { lunar: '十七', festival: null },
    '09-13': { lunar: '十八', festival: null },
    '09-14': { lunar: '十九', festival: null },
    '09-15': { lunar: '二十', festival: null },
    '09-16': { lunar: '廿一', festival: null },
    '09-17': { lunar: '廿二', festival: null },
    '09-18': { lunar: '廿三', festival: null },
    '09-19': { lunar: '廿四', festival: null },
    '09-20': { lunar: '廿五', festival: null },
    '09-21': { lunar: '廿六', festival: null },
    '09-22': { lunar: '廿七', festival: null },
    '09-23': { lunar: '廿八', festival: null },
    '09-24': { lunar: '廿九', festival: null },
    '09-25': { lunar: '三十', festival: '中秋' },
    '09-26': { lunar: '初一', festival: null },
    '09-27': { lunar: '初二', festival: null },
    '09-28': { lunar: '初三', festival: null },
    '09-29': { lunar: '初四', festival: null },
    '09-30': { lunar: '初五', festival: null },
    '10-01': { lunar: '初六', festival: null },
    '10-02': { lunar: '初七', festival: null },
    '10-03': { lunar: '初八', festival: null },
    '10-04': { lunar: '初九', festival: null },
    '10-05': { lunar: '初十', festival: null },
    '10-06': { lunar: '十一', festival: null },
    '10-07': { lunar: '十二', festival: null },
    '10-08': { lunar: '十三', festival: null },
    '10-09': { lunar: '十四', festival: null },
    '10-10': { lunar: '十五', festival: null },
    '10-11': { lunar: '十六', festival: null },
    '10-12': { lunar: '十七', festival: null },
    '10-13': { lunar: '十八', festival: null },
    '10-14': { lunar: '十九', festival: null },
    '10-15': { lunar: '二十', festival: null },
    '10-16': { lunar: '廿一', festival: null },
    '10-17': { lunar: '廿二', festival: null },
    '10-18': { lunar: '廿三', festival: null },
    '10-19': { lunar: '廿四', festival: null },
    '10-20': { lunar: '廿五', festival: null },
    '10-21': { lunar: '廿六', festival: null },
    '10-22': { lunar: '廿七', festival: null },
    '10-23': { lunar: '廿八', festival: null },
    '10-24': { lunar: '廿九', festival: null },
    '10-25': { lunar: '三十', festival: null },
    '10-26': { lunar: '初一', festival: null },
    '10-27': { lunar: '初二', festival: null },
    '10-28': { lunar: '初三', festival: null },
    '10-29': { lunar: '初四', festival: null },
    '10-30': { lunar: '初五', festival: null },
    '10-31': { lunar: '初六', festival: null },
    '11-01': { lunar: '初七', festival: null },
    '11-02': { lunar: '初八', festival: null },
    '11-03': { lunar: '初九', festival: null },
    '11-04': { lunar: '初十', festival: null },
    '11-05': { lunar: '十一', festival: null },
    '11-06': { lunar: '十二', festival: null },
    '11-07': { lunar: '十三', festival: null },
    '11-08': { lunar: '十四', festival: null },
    '11-09': { lunar: '十五', festival: null },
    '11-10': { lunar: '十六', festival: null },
    '11-11': { lunar: '十七', festival: null },
    '11-12': { lunar: '十八', festival: null },
    '11-13': { lunar: '十九', festival: null },
    '11-14': { lunar: '二十', festival: null },
    '11-15': { lunar: '廿一', festival: null },
    '11-16': { lunar: '廿二', festival: null },
    '11-17': { lunar: '廿三', festival: null },
    '11-18': { lunar: '廿四', festival: null },
    '11-19': { lunar: '廿五', festival: null },
    '11-20': { lunar: '廿六', festival: null },
    '11-21': { lunar: '廿七', festival: null },
    '11-22': { lunar: '廿八', festival: null },
    '11-23': { lunar: '廿九', festival: null },
    '11-24': { lunar: '三十', festival: null },
    '11-25': { lunar: '初一', festival: null },
    '11-26': { lunar: '初二', festival: null },
    '11-27': { lunar: '初三', festival: null },
    '11-28': { lunar: '初四', festival: null },
    '11-29': { lunar: '初五', festival: null },
    '11-30': { lunar: '初六', festival: null },
    '12-01': { lunar: '初七', festival: null },
    '12-02': { lunar: '初八', festival: null },
    '12-03': { lunar: '初九', festival: null },
    '12-04': { lunar: '初十', festival: null },
    '12-05': { lunar: '十一', festival: null },
    '12-06': { lunar: '十二', festival: null },
    '12-07': { lunar: '十三', festival: null },
    '12-08': { lunar: '十四', festival: null },
    '12-09': { lunar: '十五', festival: null },
    '12-10': { lunar: '十六', festival: null },
    '12-11': { lunar: '十七', festival: null },
    '12-12': { lunar: '十八', festival: null },
    '12-13': { lunar: '十九', festival: null },
    '12-14': { lunar: '二十', festival: null },
    '12-15': { lunar: '廿一', festival: null },
    '12-16': { lunar: '廿二', festival: null },
    '12-17': { lunar: '廿三', festival: null },
    '12-18': { lunar: '廿四', festival: null },
    '12-19': { lunar: '廿五', festival: null },
    '12-20': { lunar: '廿六', festival: null },
    '12-21': { lunar: '廿七', festival: null },
    '12-22': { lunar: '廿八', festival: null },
    '12-23': { lunar: '廿九', festival: null },
    '12-24': { lunar: '三十', festival: null },
    '12-25': { lunar: '初一', festival: null },
    '12-26': { lunar: '初二', festival: null },
    '12-27': { lunar: '初三', festival: null },
    '12-28': { lunar: '初四', festival: null },
    '12-29': { lunar: '初五', festival: null },
    '12-30': { lunar: '初六', festival: null },
    '12-31': { lunar: '初七', festival: null }
};

const IMPORTANT_FESTIVALS = [
    '除夕', '春節', '元宵', '端午', '中秋', '七夕',
    '重陽', '春節', '人日'
];

const FISTAFIFTEEN = ['初一', '十五'];

export function getLunarDate(month, day) {
    const key = `${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    return LUNAR_DATA_2026[key] || null;
}

export function getLunarDateString(dateStr) {
    const [, month, day] = dateStr.split('-');
    return getLunarDate(parseInt(month), parseInt(day));
}

export function isImportantFestival(lunarData) {
    if (!lunarData) return false;
    if (IMPORTANT_FESTIVALS.includes(lunarData.festival)) return true;
    if (lunarData.festival && lunarData.festival.includes('春節')) return true;
    return false;
}

export function isFirstOrFifteenth(lunarData) {
    if (!lunarData) return false;
    return FISTAFIFTEEN.includes(lunarData.lunar);
}

export function isLunarNewYear(lunarData) {
    if (!lunarData) return false;
    return lunarData.festival === '除夕' || lunarData.festival === '春節';
}
